# Generated by Django 4.1.1 on 2022-09-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-time_created"], "verbose_name": "Critique"},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-time_created"], "verbose_name": "Ticket"},
        ),
        migrations.AlterModelOptions(
            name="userfollows",
            options={"verbose_name": "Abonné"},
        ),
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, max_length=8192),
        ),
    ]
